### ISSUE TITLE
Segfault при использовании, отличном от дефолтного сценария

### ISSUE THREAD

**Issue by avasyukov** [vladahub/apriltree#1]
Реализация падает с segfault, например, при таком использовании:
```c++
int main()
{
    Container* c = new SimpleTree();
    delete c;
    return 0;
}
```

Падать явно не надо.

Edit: это не единственный сценарий падения. После отладки этого посмотрите сразу вокруг на предмет похожих ситуаций.

**Comment by yokomeow** [comment]
Вроде не падает больше

**Comment by avasyukov** [comment]
Вот теперь правда починено.
